version: '3.7'

networks:
  private:
    external: true
    name: "private"

services:
  schoolrank-api:
    image: schoolrank-api:latest
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: schoolrank-api
    command: bash -c "python main.py"
    networks:
      - private
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_TOKEN: ${DATABASE_TOKEN}
      DATA_SET_URL: ${DATA_SET_URL}
    volumes:
      - ./src:/usr/src

  schoolrank-grafana:
    image: grafana/grafana:latest
    container_name: schoolrank-grafana
    depends_on:
      - schoolrank-api
    networks:
      - private
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana:/var/lib/grafana
